[package]
name = "pb"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.16"
log = "0.4"
env_logger = "0.9"
once_cell = "1.10"
